# Generated by Django 3.2.15 on 2023-05-15 16:54

from django.db import migrations, models

import user_management.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user_management.models.upload_to
            ),
        ),
    ]
