# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="inspec_scan_db",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(blank=True, null=True)),
                ("rescan_id", models.TextField(blank=True, null=True)),
                ("scan_date", models.TextField(blank=True, null=True)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("project_name", models.TextField(blank=True, null=True)),
                ("total_vuln", models.IntegerField(blank=True, null=True)),
                ("scan_status", models.IntegerField(blank=True, null=True)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("total_dup", models.IntegerField(blank=True, null=True)),
                ("SEVERITY_HIGH", models.IntegerField(blank=True, null=True)),
                ("SEVERITY_MEDIUM", models.IntegerField(blank=True, null=True)),
                ("SEVERITY_LOW", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="inspec_scan_results_db",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(blank=True)),
                ("rescan_id", models.TextField(blank=True, null=True)),
                ("scan_date", models.TextField(blank=True)),
                ("project_id", models.UUIDField(blank=True)),
                ("vuln_id", models.UUIDField(blank=True)),
                ("false_positive", models.TextField(blank=True, null=True)),
                ("vul_col", models.TextField(blank=True)),
                ("dup_hash", models.TextField(blank=True, null=True)),
                ("vuln_duplicate", models.TextField(blank=True, null=True)),
                ("false_positive_hash", models.TextField(blank=True, null=True)),
                ("vuln_status", models.TextField(blank=True, null=True)),
                ("Name", models.TextField(blank=True, null=True)),
                ("platform_name", models.TextField(blank=True, null=True)),
                ("platform_release", models.TextField(blank=True, null=True)),
                ("profiles_name", models.TextField(blank=True, null=True)),
                ("profiles_sha256", models.TextField(blank=True, null=True)),
                ("profiles_title", models.TextField(blank=True, null=True)),
                ("profiles_supports", models.TextField(blank=True, null=True)),
                ("attributes_name", models.TextField(blank=True, null=True)),
                (
                    "attributes_options_description",
                    models.TextField(blank=True, null=True),
                ),
                ("attributes_options_default", models.TextField(blank=True, null=True)),
                ("groups_id", models.TextField(blank=True, null=True)),
                ("groups_controls", models.TextField(blank=True, null=True)),
                ("controls_id", models.TextField(blank=True, null=True)),
                ("controls_title", models.TextField(blank=True, null=True)),
                ("controls_desc", models.TextField(blank=True, null=True)),
                ("controls_descriptions", models.TextField(blank=True, null=True)),
                ("controls_impact", models.TextField(blank=True, null=True)),
                ("controls_refs", models.TextField(blank=True, null=True)),
                ("controls_tags_severity", models.TextField(blank=True, null=True)),
                ("controls_tags_cis_id", models.TextField(blank=True, null=True)),
                ("controls_tags_cis_control", models.TextField(blank=True, null=True)),
                ("controls_tags_cis_level", models.TextField(blank=True, null=True)),
                ("controls_tags_audit", models.TextField(blank=True, null=True)),
                ("controls_tags_fix", models.TextField(blank=True, null=True)),
                ("controls_tags_defaultvalue", models.TextField(blank=True, null=True)),
                ("controls_code", models.TextField(blank=True, null=True)),
                ("controls_source_location", models.TextField(blank=True, null=True)),
                ("controls_results_status", models.TextField(blank=True, null=True)),
                ("controls_results_code_desc", models.TextField(blank=True, null=True)),
                ("controls_results_run_time", models.TextField(blank=True, null=True)),
                (
                    "controls_results_start_time",
                    models.TextField(blank=True, null=True),
                ),
                ("controls_results_message", models.TextField(blank=True, null=True)),
                ("scanner", models.TextField(default="inspec", editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name="inspec_scans_db",
        ),
    ]
