# Generated by Django 3.1.2 on 2020-10-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_auto_20201006_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspec_scan_db',
            old_name='SEVERITY_LOW',
            new_name='low_vul',
        ),
    ]
