# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.TextField(blank=True)),
                ('project_name', models.TextField(blank=True)),
                ('project_start', models.TextField(blank=True)),
                ('project_end', models.TextField(blank=True)),
                ('project_owner', models.TextField(blank=True)),
                ('project_disc', models.TextField(blank=True)),
                ('project_status', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_scan_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.TextField(blank=True)),
                ('project_ip', models.TextField(blank=True)),
                ('scan_type', models.TextField(blank=True)),
                ('project_id', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
