# Generated by Django 3.1.2 on 2020-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_db_total_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_db',
            name='total_close',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project_db',
            name='total_net',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project_db',
            name='total_open',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project_db',
            name='total_static',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project_db',
            name='total_web',
            field=models.TextField(null=True),
        ),
    ]
