# Generated by Django 3.1.2 on 2020-04-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_db_total_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(blank=True)),
                ('high', models.TextField(blank=True)),
                ('medium', models.TextField(blank=True)),
                ('low', models.TextField(blank=True)),
            ],
        ),
    ]
