# Generated by Django 3.1.2 on 2020-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_month_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_db',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
