# Generated by Django 3.1.2 on 2020-05-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_month_db_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_db',
            name='project_id',
            field=models.TextField(blank=True),
        ),
    ]
