# Generated by Django 3.1.2 on 2020-10-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_auto_20201010_1912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month_db",
            name="high",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="month_db",
            name="low",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="month_db",
            name="medium",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="month_db",
            name="project_id",
            field=models.TextField(blank=True, default=0),
        ),
    ]
