#!/usr/bin/env python
from setuptools import setup

setup(
    name='ArcherySec',
    version='0.1',
    author='Anand Tiwari',
    description="Tool for managing and scanning vulnerability",
    install_requires=[
        'djangorestframework-jwt',
        'asn1crypto==0.23.0',
        'certifi==2017.11.5',
        'cffi==1.11.2',
        'chardet==3.0.4',
        'cryptography==2.3',
        'Django',
        'django-appconf==1.0.2',
        'django-cryptography==0.2',
        'django-fernet-fields==0.5',
        'django-stronghold==0.2.9',
        'enum34==1.1.6',
        'idna==2.6',
        'ipaddress==1.0.18',
        'openvas-lib==1.1.3',
        'pycparser==2.18',
        'python-owasp-zap-v2.4==0.0.13',
        'pytz==2017.3',
        'requests==2.20.0',
        'selenium==3.8.0',
        'six==1.11.0',
        'urllib3',
        'coreapi==2.3.3',
        'coreapi-cli==1.0.6',
        'djangorestframework==3.7.7',
        'django-easy-pdf==0.1.1',
        'WeasyPrint==0.42',
        'PyBurprestapi==0.1',
        'xhtml2pdf==0.2b1',
    ],
    url='https://github.com/anandtiwarics/archerysec/'
)
