# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='osint_domain_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.TextField(blank=True)),
                ('sub_domains', models.TextField(blank=True)),
                ('project_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='osint_whois_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('expiration_date', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True)),
                ('domain_name', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('whois_server', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('registrar', models.TextField(blank=True, null=True)),
                ('referral_url', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('name_servers', models.TextField(blank=True, null=True)),
                ('org', models.TextField(blank=True, null=True)),
                ('creation_date', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
