# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_token_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(blank=True)),
                ('scan_url', models.URLField(blank=True)),
                ('scan_id', models.UUIDField(blank=True)),
                ('api_token', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIScan_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(blank=True)),
                ('scan_url', models.URLField(blank=True)),
                ('scan_id', models.UUIDField(blank=True)),
                ('req_header', models.TextField(blank=True)),
                ('req_body', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('auth_url', models.CharField(blank=True, max_length=10)),
                ('auth_token_key', models.TextField(blank=True)),
                ('extra_vaule_auth', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIScan_url_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(blank=True)),
                ('scan_url', models.URLField(blank=True)),
                ('scan_id', models.UUIDField(blank=True)),
                ('req_header', models.TextField(blank=True)),
                ('req_body', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('auth_url', models.CharField(blank=True, max_length=10)),
                ('auth_token_key', models.TextField(blank=True)),
                ('extra_vaule_auth', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
