# Generated by Django 3.2.15 on 2023-05-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
        ("archeryapi", "0002_orgapikey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgapikey",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_management.organization",
            ),
        ),
    ]
