# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='openvas_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openvas_host', models.TextField(blank=True)),
                ('openvas_port', models.IntegerField(blank=True)),
                ('openvas_enabled', models.BooleanField(blank=True)),
                ('openvas_user', models.TextField(blank=True)),
                ('openvas_password', django_cryptography.fields.encrypt(models.CharField(verbose_name=models.CharField(max_length=500)))),
            ],
        ),
        migrations.CreateModel(
            name='ov_scan_result_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.TextField(blank=True)),
                ('vul_id', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('owner', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('creation_time', models.TextField(blank=True)),
                ('modification_time', models.TextField(blank=True)),
                ('user_tags', models.TextField(blank=True)),
                ('host', models.TextField(blank=True)),
                ('port', models.TextField(blank=True)),
                ('nvt', models.TextField(blank=True)),
                ('scan_nvt_version', models.TextField(blank=True)),
                ('threat', models.TextField(blank=True)),
                ('severity', models.TextField(blank=True)),
                ('qod', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('term', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('field', models.TextField(blank=True)),
                ('filtered', models.TextField(blank=True)),
                ('page', models.TextField(blank=True)),
                ('family', models.TextField(blank=True)),
                ('cvss_base', models.TextField(blank=True)),
                ('cve', models.TextField(blank=True)),
                ('bid', models.TextField(blank=True)),
                ('xref', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('banner', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='scan_save_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.TextField(blank=True)),
                ('scan_ip', models.TextField(blank=True)),
                ('target_id', models.TextField(blank=True)),
                ('scan_status', models.TextField(blank=True)),
                ('total_vul', models.TextField(blank=True)),
                ('high_total', models.TextField(blank=True)),
                ('medium_total', models.TextField(blank=True)),
                ('low_total', models.TextField(blank=True)),
            ],
        ),
    ]