# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkscanners", "0004_auto_20190207_0342"),
    ]

    operations = [
        migrations.AddField(
            model_name="nessus_scan_db",
            name="info_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
