# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0004_auto_20190125_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nessus_report_db',
            name='scanner',
            field=models.TextField(default='Nessus', editable=False),
        ),
        migrations.AlterField(
            model_name='ov_scan_result_db',
            name='scanner',
            field=models.TextField(default='OpenVAS', editable=False),
        ),
    ]
