# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkscanners", "0005_nessus_scan_db_info_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan_save_db",
            name="log_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
