# Generated by Django 3.1.1 on 2020-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("networkscanners", "0008_auto_20200503_1201"),
    ]

    operations = [
        migrations.CreateModel(
            name="nessus_scan_results_db",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(blank=True)),
                ("rescan_id", models.TextField(blank=True, null=True)),
                ("scan_date", models.TextField(blank=True)),
                ("project_id", models.UUIDField(blank=True)),
                ("vuln_id", models.UUIDField(blank=True)),
                ("false_positive", models.TextField(blank=True, null=True)),
                ("vul_col", models.TextField(blank=True)),
                ("dup_hash", models.TextField(blank=True, null=True)),
                ("vuln_duplicate", models.TextField(blank=True, null=True)),
                ("false_positive_hash", models.TextField(blank=True, null=True)),
                ("vuln_status", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cve", models.TextField(blank=True, null=True)),
                ("gl_scanner", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("file", models.TextField(blank=True, null=True)),
                ("identifiers", models.TextField(blank=True, null=True)),
                ("Severity", models.TextField(blank=True, null=True)),
                ("jira_ticket", models.TextField(blank=True, null=True)),
                ("scanner", models.TextField(default="nessus", editable=False)),
                ("username", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="nessus_scan_db",
            name="SEVERITY_HIGH",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nessus_scan_db",
            name="SEVERITY_LOW",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nessus_scan_db",
            name="SEVERITY_MEDIUM",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nessus_scan_db",
            name="project_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nessus_scan_db",
            name="scan_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nessus_scan_db",
            name="total_vuln",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
