# Generated by Django 3.1.1 on 2020-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0009_auto_20201002_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='Severity',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='cve',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='file',
            new_name='pluginFamily',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='gl_scanner',
            new_name='pluginID',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='identifiers',
            new_name='pluginName',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='location',
            new_name='plugin_modification_date',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='message',
            new_name='plugin_name',
        ),
        migrations.RenameField(
            model_name='nessus_scan_results_db',
            old_name='name',
            new_name='plugin_output',
        ),
        migrations.AddField(
            model_name='nessus_scan_db',
            name='report_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_db',
            name='target',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='plugin_publication_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='plugin_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='port',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='protocol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='report_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='risk_factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='scan_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='script_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='see_also',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='severity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='severity_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='svc_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='vul_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nessus_scan_results_db',
            name='scanner',
            field=models.TextField(default='Nessus', editable=False),
        ),
    ]
