# Generated by Django 3.1.2 on 2020-10-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0013_nessus_targets_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessus_report_db',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessus_scan_results_db',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
