# Generated by Django 3.1.2 on 2020-10-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanners', '0016_auto_20201006_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nessus_scan_db',
            old_name='total_vul',
            new_name='total_vuln',
        ),
    ]
