# Generated by Django 3.1.8 on 2021-05-14 19:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networkscanners", "0017_auto_20201006_1440"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkScanDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("rescan_id", models.TextField(blank=True, null=True)),
                ("scan_date", models.TextField(blank=True)),
                ("scan_status", models.TextField(blank=True)),
                ("project_id", models.UUIDField(blank=True)),
                ("total_vul", models.IntegerField(blank=True, null=True)),
                ("critical_vul", models.IntegerField(blank=True, null=True)),
                ("high_vul", models.IntegerField(blank=True, null=True)),
                ("medium_vul", models.IntegerField(blank=True, null=True)),
                ("low_vul", models.IntegerField(blank=True, null=True)),
                ("info_vul", models.IntegerField(blank=True, null=True)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("rescan", models.TextField(blank=True, null=True)),
                ("total_dup", models.TextField(blank=True, null=True)),
                ("username", models.CharField(max_length=256, null=True)),
                ("scanner", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkScanResultsDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_id",
                    models.TextField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("project_id", models.UUIDField(null=True)),
                ("vuln_id", models.UUIDField(blank=True)),
                ("title", models.TextField(blank=True)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("severity_color", models.CharField(max_length=256, null=True)),
                ("severity", models.CharField(max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("solution", models.TextField(blank=True, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("scanner", models.TextField()),
                ("username", models.CharField(max_length=256, null=True)),
                ("jira_ticket", models.TextField(blank=True, null=True)),
                ("dup_hash", models.TextField(blank=True, null=True)),
                ("vuln_duplicate", models.TextField(blank=True, null=True)),
                ("false_positive", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
