# Generated by Django 3.2.15 on 2022-08-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudscanners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudscansdb',
            old_name='project_name',
            new_name='cloudAccountId',
        ),
    ]
