# Generated by Django 3.1.12 on 2021-07-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210719_1431'),
        ('manual_scan', '0013_manual_scan_results_db_pentest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualScanResultsDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.TextField(blank=True)),
                ('scan_id', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('rescan_id', models.TextField(blank=True, null=True)),
                ('vuln_name', models.TextField(blank=True, null=True)),
                ('severity', models.TextField(blank=True, null=True)),
                ('severity_color', models.TextField(blank=True, null=True)),
                ('vuln_url', models.TextField(blank=True, null=True)),
                ('scan_url', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('request_header', models.TextField(blank=True, null=True)),
                ('response_header', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('vuln_status', models.TextField(blank=True, null=True)),
                ('Poc_Img', models.ImageField(blank=True, null=True, upload_to='')),
                ('poc_description', models.TextField(blank=True, null=True)),
                ('pentest_type', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb')),
            ],
        ),
        migrations.CreateModel(
            name='ManualScansDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_url', models.URLField(blank=True)),
                ('scan_id', models.TextField(blank=True)),
                ('total_vul', models.IntegerField(blank=True, null=True)),
                ('high_vul', models.IntegerField(blank=True, null=True)),
                ('medium_vul', models.IntegerField(blank=True, null=True)),
                ('low_vul', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('pentest_type', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb')),
            ],
        ),
        migrations.DeleteModel(
            name='manual_scan_results_db',
        ),
        migrations.DeleteModel(
            name='manual_scans_db',
        ),
        migrations.RemoveField(
            model_name='vulnerabilitydata',
            name='username',
        ),
    ]
