# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jirasetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_server", models.TextField(blank=True, null=True)),
                ("jira_username", models.TextField(blank=True, null=True)),
                ("jira_password", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
