# Generated by Django 3.1.12 on 2021-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jirasetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("jira_server", models.TextField(blank=True, null=True)),
                ("jira_username", models.TextField(blank=True, null=True)),
                ("jira_password", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
