# Generated by Django 2.1.8 on 2020-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiraticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirasetting',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
