# Generated by Django 3.1.12 on 2021-07-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraticketing', '0003_jirasetting_setting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jirasetting',
            name='username',
        ),
    ]
