# Generated by Django 3.1.12 on 2021-08-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0015_auto_20210719_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicdDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicd_id', models.UUIDField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('threshold', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('threshold_count', models.IntegerField(blank=True, null=True)),
                ('build_id', models.TextField(blank=True, null=True)),
                ('commit_hash', models.TextField(blank=True, null=True)),
                ('branch_tag', models.TextField(blank=True, null=True)),
                ('repo', models.URLField(blank=True, null=True)),
                ('scm_server', models.TextField(blank=True, null=True)),
                ('build_server', models.TextField(blank=True, null=True)),
                ('total_vul', models.IntegerField(blank=True, null=True)),
                ('critical_vul', models.IntegerField(blank=True, null=True)),
                ('high_vul', models.IntegerField(blank=True, null=True)),
                ('medium_vul', models.IntegerField(blank=True, null=True)),
                ('low_vul', models.IntegerField(blank=True, null=True)),
                ('info_vul', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb')),
            ],
            options={
                'verbose_name_plural': 'CI/CD',
                'db_table': 'cicddb',
            },
        ),
    ]
