# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscanners', '0002_auto_20181031_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='acunetix_scan_result_db',
            name='scanner',
            field=models.TextField(default='Acunetix', editable=False),
        ),
        migrations.AddField(
            model_name='arachni_scan_result_db',
            name='scanner',
            field=models.TextField(default='Arachni', editable=False),
        ),
        migrations.AddField(
            model_name='burp_scan_result_db',
            name='scanner',
            field=models.TextField(default='Burp Scanner', editable=False),
        ),
        migrations.AddField(
            model_name='netsparker_scan_result_db',
            name='scanner',
            field=models.TextField(default='Netsparker', editable=False),
        ),
        migrations.AddField(
            model_name='webinspect_scan_result_db',
            name='scanner',
            field=models.TextField(default='Webinspect', editable=False),
        ),
        migrations.AddField(
            model_name='zap_scan_results_db',
            name='scanner',
            field=models.TextField(default='ZAP Scanner', editable=False),
        ),
    ]
