# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscanners', '0003_auto_20190125_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acunetix_scan_result_db',
            name='scanner',
            field=models.TextField(default='Acunetix', editable=False),
        ),
        migrations.AlterField(
            model_name='arachni_scan_result_db',
            name='scanner',
            field=models.TextField(default='Arachni', editable=False),
        ),
        migrations.AlterField(
            model_name='burp_scan_result_db',
            name='scanner',
            field=models.TextField(default='Burp Scanner', editable=False),
        ),
        migrations.AlterField(
            model_name='netsparker_scan_result_db',
            name='scanner',
            field=models.TextField(default='Netsparker', editable=False),
        ),
        migrations.AlterField(
            model_name='webinspect_scan_result_db',
            name='scanner',
            field=models.TextField(default='Webinspect', editable=False),
        ),
        migrations.AlterField(
            model_name='zap_scan_results_db',
            name='scanner',
            field=models.TextField(default='ZAP Scanner', editable=False),
        ),
    ]
