# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-26 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscanners", "0004_zap_scans_db_info_vul"),
    ]

    operations = [
        migrations.AddField(
            model_name="arachni_scan_db",
            name="info_vul",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
