# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-26 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0005_arachni_scan_db_info_vul"),
    ]

    operations = [
        migrations.AddField(
            model_name="burp_scan_db",
            name="info_vul",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
