# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscanners", "0014_auto_20190409_0540"),
    ]

    operations = [
        migrations.AddField(
            model_name="burp_issue_definitions",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
    ]
