# Generated by Django 2.1.8 on 2020-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0016_burp_issue_definitions_vulnerability_classifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="acunetix_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="acunetix_scan_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="arachni_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="arachni_scan_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="burp_issue_definitions",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="burp_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="burp_scan_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="cookie_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="email_config_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="excluded_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="netsparker_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="netsparker_scan_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="task_schedule_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="web_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="webinspect_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="webinspect_scan_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="zap_scan_results_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="zap_scans_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="zap_spider_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="zap_spider_results",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
