# Generated by Django 3.1.5 on 2021-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0018_auto_20201004_1522"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebScanResultsDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vuln_id", models.UUIDField(blank=True)),
                ("scan_id", models.UUIDField(blank=True)),
                ("rescan_id", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True)),
                ("name", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("project_id", models.TextField(blank=True)),
                ("severity_color", models.TextField(blank=True)),
                ("severity", models.TextField(blank=True, null=True)),
                ("date_time", models.DateTimeField(null=True)),
                ("false_positive", models.TextField(blank=True, null=True)),
                ("jira_ticket", models.TextField(blank=True, null=True)),
                ("vuln_status", models.TextField(blank=True, null=True)),
                ("dup_hash", models.TextField(blank=True, null=True)),
                ("vuln_duplicate", models.TextField(blank=True, null=True)),
                ("false_positive_hash", models.TextField(blank=True, null=True)),
                ("scanner", models.TextField(editable=False)),
                ("username", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebScansDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_url", models.URLField(blank=True)),
                ("scan_id", models.UUIDField(blank=True)),
                ("rescan_id", models.TextField(blank=True, null=True)),
                ("scan_date", models.TextField(blank=True)),
                ("scan_status", models.TextField(blank=True)),
                ("project_id", models.UUIDField(blank=True)),
                ("total_vul", models.IntegerField(blank=True, null=True)),
                ("critical_vul", models.IntegerField(blank=True, null=True)),
                ("high_vul", models.IntegerField(blank=True, null=True)),
                ("medium_vul", models.IntegerField(blank=True, null=True)),
                ("low_vul", models.IntegerField(blank=True, null=True)),
                ("info_vul", models.IntegerField(blank=True, null=True)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("rescan", models.TextField(blank=True, null=True)),
                ("total_dup", models.TextField(blank=True, null=True)),
                ("username", models.CharField(max_length=256, null=True)),
                ("scanner", models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
