# Generated by Django 3.1.5 on 2021-01-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscanners', '0019_webscanresultsdb_webscansdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webscanresultsdb',
            old_name='name',
            new_name='title',
        ),
    ]
