# Generated by Django 3.1.8 on 2021-05-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscanners', '0021_auto_20210130_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zap_scan_results_db',
        ),
        migrations.DeleteModel(
            name='zap_scans_db',
        ),
        migrations.DeleteModel(
            name='zap_spider_results',
        ),
    ]
