# Generated by Django 3.1.8 on 2021-05-06 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0022_auto_20210506_1634"),
    ]

    operations = [
        migrations.DeleteModel(
            name="burp_scan_db",
        ),
    ]
