# Generated by Django 3.1.12 on 2021-07-19 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210719_1431'),
        ('webscanners', '0025_burp_issue_definitions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webscanresultsdb',
            options={'verbose_name_plural': 'Web Scan Result Data'},
        ),
        migrations.AlterModelOptions(
            name='webscansdb',
            options={'verbose_name_plural': 'Web Scans'},
        ),
        migrations.RemoveField(
            model_name='burp_issue_definitions',
            name='username',
        ),
        migrations.RemoveField(
            model_name='cookie_db',
            name='username',
        ),
        migrations.RemoveField(
            model_name='email_config_db',
            name='username',
        ),
        migrations.RemoveField(
            model_name='excluded_db',
            name='username',
        ),
        migrations.RemoveField(
            model_name='task_schedule_db',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='task_schedule_db',
            name='username',
        ),
        migrations.RemoveField(
            model_name='web_scan_db',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='web_scan_db',
            name='username',
        ),
        migrations.RemoveField(
            model_name='webscanresultsdb',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='webscanresultsdb',
            name='username',
        ),
        migrations.RemoveField(
            model_name='webscansdb',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='webscansdb',
            name='username',
        ),
        migrations.RemoveField(
            model_name='zap_spider_db',
            name='username',
        ),
        migrations.AddField(
            model_name='task_schedule_db',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='web_scan_db',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='reated_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webscansdb',
            name='scanner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='webscanresultsdb',
            table='webscanResultsdb',
        ),
        migrations.AlterModelTable(
            name='webscansdb',
            table='webscandb',
        ),
    ]
