# Generated by Django 3.2.15 on 2022-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscanners", "0027_web_scan_db_critical_vul"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscanresultsdb",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
