# Generated by Django 3.2.15 on 2023-05-06 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
        ('webscanners', '0028_webscanresultsdb_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webscansdb',
            name='reated_time',
        ),
        migrations.AddField(
            model_name='burp_issue_definitions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burp_issue_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='burp_issue_definitions',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='burp_issue_definitions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='burp_issue_definitions',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='burp_issue_definitions',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burp_issue_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email_config_db',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_config_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email_config_db',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='email_config_db',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='email_config_db',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='email_config_db',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_config_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_schedule_db',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_sch_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_schedule_db',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task_schedule_db',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task_schedule_db',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='task_schedule_db',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_sch_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='web_scan_db',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_scans_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='web_scan_db',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='web_scan_db',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='web_scan_db',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='web_scan_db',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_scans_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_scan_result_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='webscanresultsdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_scan_result_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_scan_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='webscansdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_scan_db_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
