# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='burp_setting_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burp_url', models.TextField(blank=True, null=True)),
                ('burp_port', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nmap_vulners_setting_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.NullBooleanField()),
                ('version', models.NullBooleanField()),
                ('online', models.NullBooleanField()),
                ('timing', models.IntegerField(blank=0, null=0)),
            ],
        ),
        migrations.CreateModel(
            name='openvas_setting_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(blank=True, null=True)),
                ('port', models.IntegerField(blank=9390, null=9390)),
                ('enabled', models.NullBooleanField()),
                ('user', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zap_settings_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zap_url', models.TextField(blank=True, null=True)),
                ('zap_api', models.TextField(blank=True, null=True)),
                ('zap_port', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
