# Generated by Django 3.1.12 on 2021-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArachniSettingsDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("arachni_url", models.TextField(blank=True, null=True)),
                ("arachni_port", models.TextField(blank=True, null=True)),
                ("arachni_user", models.TextField(blank=True, null=True)),
                ("arachni_pass", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BurpSettingDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("burp_url", models.TextField(blank=True, null=True)),
                ("burp_port", models.TextField(blank=True, null=True)),
                ("burp_api_key", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("recipient_list", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="NmapVulnersSettingDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("enabled", models.BooleanField()),
                ("version", models.BooleanField()),
                ("online", models.BooleanField()),
                ("timing", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OpenvasSettingDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("host", models.TextField(blank=True, null=True)),
                ("port", models.IntegerField(default=9390)),
                ("enabled", models.BooleanField()),
                ("user", models.TextField(blank=True, null=True)),
                ("password", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SettingsDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("setting_name", models.TextField(blank=True, null=True)),
                ("setting_scanner", models.TextField(blank=True, null=True)),
                ("setting_status", models.BooleanField(blank=True, null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZapSettingsDb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_id", models.UUIDField(blank=True, null=True)),
                ("zap_url", models.TextField(default="127.0.0.1")),
                ("zap_api", models.TextField(default="dwed23wdwedwwefw4rwrfw")),
                ("zap_port", models.IntegerField(default=8090)),
                ("enabled", models.BooleanField()),
            ],
        ),
    ]
