# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arachni_settings_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arachni_url', models.TextField(blank=True, null=True)),
                ('arachni_port', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
