# Generated by Django 3.2.15 on 2023-05-06 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
        ('archerysettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arachnisettingsdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arachni_settings_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arachnisettingsdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arachnisettingsdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arachnisettingsdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='arachnisettingsdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arachni_settings_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='burpsettingdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burp_settings_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='burpsettingdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='burpsettingdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='burpsettingdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='burpsettingdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burp_settings_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaildb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaildb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emaildb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emaildb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='emaildb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nmapvulnerssettingdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nmap_vulner_settings_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nmapvulnerssettingdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nmapvulnerssettingdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nmapvulnerssettingdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='nmapvulnerssettingdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nmap_vulner_settings_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openvassettingdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openvas_settings_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openvassettingdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='openvassettingdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='openvassettingdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='openvassettingdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openvas_settings_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zap_settings_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='zapsettingsdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zap_settings_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settingsdb',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
