# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archerysettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zap_settings_db",
            name="zap_api",
            field=models.TextField(default="dwed23wdwedwwefw4rwrfw"),
        ),
        migrations.AlterField(
            model_name="zap_settings_db",
            name="zap_port",
            field=models.IntegerField(default=8090),
        ),
    ]
