# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0002_arachni_settings_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmap_vulners_setting_db',
            name='timing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openvas_setting_db',
            name='port',
            field=models.IntegerField(default=9390),
        ),
    ]
