# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0004_email_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_db',
            name='recipient_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
