# Generated by Django 3.1.12 on 2021-07-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0004_auto_20210407_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('setting_name', models.TextField(blank=True, null=True)),
                ('setting_scanner', models.TextField(blank=True, null=True)),
                ('setting_status', models.BooleanField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='arachni_settings_db',
            name='setting_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burp_setting_db',
            name='setting_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email_db',
            name='setting_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nmap_vulners_setting_db',
            name='setting_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openvas_setting_db',
            name='setting_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zap_settings_db',
            name='setting_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
