# Generated by Django 3.1.12 on 2021-07-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0005_auto_20210714_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_db',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
