# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archerysettings', '0005_auto_20190311_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='burp_setting_db',
            name='burp_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
