# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticscanners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='retirejs_scan_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(blank=True, null=True)),
                ('rescan_id', models.TextField(blank=True, null=True)),
                ('scan_date', models.TextField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('source_line', models.TextField(blank=True, null=True)),
                ('total_vuln', models.TextField(blank=True, null=True)),
                ('SEVERITY_HIGH', models.TextField(blank=True, null=True)),
                ('SEVERITY_MEDIUM', models.TextField(blank=True, null=True)),
                ('SEVERITY_LOW', models.TextField(blank=True, null=True)),
                ('scan_status', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('total_dup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='retirejs_scan_results_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(blank=True)),
                ('rescan_id', models.TextField(blank=True, null=True)),
                ('scan_date', models.TextField(blank=True)),
                ('project_id', models.UUIDField(blank=True)),
                ('vuln_id', models.UUIDField(blank=True)),
                ('file', models.TextField(blank=True)),
                ('component', models.TextField(blank=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('CVE', models.TextField(blank=True)),
                ('bug', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('severity', models.TextField(blank=True)),
                ('dup_hash', models.TextField(blank=True, null=True)),
                ('vuln_duplicate', models.TextField(blank=True, null=True)),
                ('false_positive_hash', models.TextField(blank=True, null=True)),
                ('vuln_status', models.TextField(blank=True, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bandit_scan_db',
            name='total_dup',
            field=models.TextField(blank=True, null=True),
        ),
    ]