# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticscanners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencycheck_scan_results_db',
            name='scanner',
            field=models.TextField(default='Dependency Check', editable=False),
        ),
    ]
