# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staticscanners", "0013_auto_20191026_0918"),
        ("staticscanners", "0013_trivy_scan_db_trivy_scan_results_db"),
    ]

    operations = []
