# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticscanners", "0019_auto_20200503_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodejsscan_scan_results_db",
            name="jira_ticket",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="npmaudit_scan_results_db",
            name="jira_ticket",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfsec_scan_results_db",
            name="jira_ticket",
            field=models.TextField(blank=True, null=True),
        ),
    ]
