# Generated by Django 2.1.8 on 2020-08-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticscanners", "0021_whitesource_scan_db_whitesource_scan_results_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitesource_scan_results_db",
            name="filename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whitesource_scan_results_db",
            name="groupId",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whitesource_scan_results_db",
            name="sha1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whitesource_scan_results_db",
            name="version",
            field=models.TextField(blank=True, null=True),
        ),
    ]
