# Generated by Django 3.1.2 on 2020-10-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staticscanners", "0031_auto_20201006_1432"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bandit_scan_db",
            old_name="SEVERITY_LOW",
            new_name="low_vul",
        ),
    ]
