# Generated by Django 3.2.15 on 2022-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staticscanners", "0036_auto_20210719_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticscanresultsdb",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
