# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nikto_result_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('scan_url', models.TextField(blank=True, null=True)),
                ('nikto_scan_output', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nmap_result_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('protocol', models.TextField(blank=True, null=True)),
                ('port', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reason_ttl', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('extrainfo', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('conf', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('type_p', models.TextField(blank=True, null=True)),
                ('osfamily', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('osgen', models.TextField(blank=True, null=True)),
                ('accuracy', models.TextField(blank=True, null=True)),
                ('cpe', models.TextField(blank=True, null=True)),
                ('used_state', models.TextField(blank=True, null=True)),
                ('used_portid', models.TextField(blank=True, null=True)),
                ('used_proto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nmap_scan_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('scan_ip', models.TextField(blank=True, null=True)),
                ('total_ports', models.TextField(blank=True, null=True)),
                ('total_open_ports', models.TextField(blank=True, null=True)),
                ('total_close_ports', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sslscan_result_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('scan_url', models.TextField(blank=True, null=True)),
                ('sslscan_output', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nmap_vulners_port_result_db',
            fields=[
                ('nmap_result_db_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.nmap_result_db')),
                ('vulners_extrainfo', models.TextField(blank=True, null=True)),
            ],
            bases=('tools.nmap_result_db',),
        ),
    ]
