# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nikto_vuln_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(blank=True, null=True)),
                ('targetip', models.TextField(blank=True, null=True)),
                ('hostname', models.TextField(blank=True, null=True)),
                ('port', models.TextField(blank=True, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('httpmethod', models.TextField(blank=True, null=True)),
                ('testlinks', models.TextField(blank=True, null=True)),
                ('osvdb', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
