# Generated by Django 2.1.8 on 2020-05-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_auto_20190207_0342"),
    ]

    operations = [
        migrations.AddField(
            model_name="nikto_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="nikto_vuln_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="nmap_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="nmap_scan_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="sslscan_result_db",
            name="username",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
