# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_nikto_vuln_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikto_vuln_db',
            name='project_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nikto_vuln_db',
            name='scan_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nikto_vuln_db',
            name='scan_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
