# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20190110_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikto_vuln_db',
            name='date_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
